public class StudentTester
{
    public static readonly List<Student> Students = [];

    public static void Main()
    {
        // This data could have been read in from a file
        List<(string Name, int Age)> data = [
            ("Alice", 22),
            ("Tim", -10),
            ("Rita", -1),
            ("Phil", 0),
            ("Bob", 200),
            ("Lisa", 201),
            ("Jim", 1000),
            ("", 21),
            (null, 33),
            ("", -16),
        ];

        foreach (var datum in data)
        {
            AddStudent(datum);
        }

        foreach (var datum in data)
        {
            AddStudentNoExceptions(datum);
        }
    }

    /*
        The method AddStudent takes in a student tuple and tries
        to add it to the student list. If it cannot, we catch both
        possible exceptions (not Exception). Regardless of success or
        failure, we state the tuple has been processed.
        Notice that the order of the exceptions matters.

        To print out tuple in a nice way:
        Console.Write($"(\"{student.Name ?? "null"}\", {student.Age}):\t");

        ??: null-coalescing operator. It provides a default value when 
        the left-hand operand is null.
    */
    public static void AddStudent((string Name, int Age) student)
    {
        Console.Write($"(\"{student.Name ?? "null"}\", {student.Age}):\t");
        // Put code that can cause an exception in a try block
        try
        {
            Student s = new(student.Name, student.Age);
            Students.Add(s);
            Console.Write($"Added. ");
        }
        // If the code in try fails then the appropriate catch block will be executed
        // When possible it is better to catch specific exceptions
        // catch (Exception ex)
        catch (ArgumentOutOfRangeException ex)
        {
            Console.Write($"Not added due to age - {ex.Message}. ");
        }
        /*            
            Notice that the order matters.
            Catch blocks are evaluated top-down. 
            If a more general exception type (like ArgumentException) 
            appears before a more specific one (ArgumentOutOfRangeException), 
            the specific block becomes unreachable, causing a compile-time error.
         */
        catch (ArgumentException ex)
        {
            Console.Write($"Not added due to name - {ex.Message}. ");
        }
        finally
        {
            Console.WriteLine("Processed.");
        }
    }

    /*
        Exception handling should only be used in EXCEPTIONAL cases.
        
        Exceptions should be used to handle unexpected errors 
        that your code cannot easily predict or recover from as 
        using exceptions can impact performance and readability.

        For example, when dealing with resources like files, 
        network connections, or database connections, 
        exceptions can help handle unexpected errors
        and ensure that resources are properly released 
        even if an error occurs.

        You should avoid relying on exceptions for regular control flow.
        Validation logic is preferred when input can be anticipated or controlled.
        For example, the AddStudent method could be rewritten as below. 

        Even exceptions generated by Convert.ToInt32 can be avoided by using 
        int.TryParse, which allows safe conversion without throwing.
    */
    public static void AddStudentNoExceptions((string Name, int Age) student)
    {
        Console.Write($"(\"{student.Name ?? "null"}\", {student.Age}):\t");
        if (string.IsNullOrWhiteSpace(student.Name))
        {
            Console.WriteLine("Not Added. Name cannot be null or empty.");
            return;
        }
        if (student.Age < 0 || student.Age > 200)
        {
            Console.WriteLine("Not Added. Age must be 0-200.");
            return;
        }
        Student s = new Student(student.Name, student.Age);
        Students.Add(s);
        Console.WriteLine($"Added.");
    }
}