/*
    Some exceptions that you encounter are generated by 
    the classes that you use when certain problems arise.

    For example in the Convert class,
    the ToInt32 method throws exceptions
    https://learn.microsoft.com/en-us/dotnet/api/system.convert.toint32

    The following is a simplified example of a class that
    throws an exception. This Student class was developed 
    for an application where it is critical that each student 
    has a valid name and age.

    To enforce this, exceptions are thrown to prevent the 
    creation of Student objects with invalid data.

    Not all classes require this level of validation. 
    In less strict scenarios, values like an empty string 
    for name or zero for age might be acceptable, 
    and exceptions could be avoided.

    As a general guideline, exceptions should only be used 
    when invalid data would lead to significant issues.

    Exceptions are primarily intended to help developers 
    detect and handle errors in code. In production 
    applications, exceptions should be caught and handled 
    gracefully so that end users are not exposed to 
    technical error messages.
*/


public class Student
{
    public string Name;
    public int Age;

    public Student(string name, int age)
    {
        SetName(name);
        SetAge(age);
    }

    public void SetName(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            /* 
                The throw statement throws an exception.

                You should throw the most specific exception type 
                available to clearly communicate the nature of the 
                error. Avoid throwing the base Exception type 
                unless there's no more appropriate alternative, 
                as it provides limited context and makes error 
                handling less precise.

                Ensure your message is detailed so that the error 
                can be easily resolved. Avoid messages like "Error".
            */
            // Most general type of exception
            // throw new Exception("Name cannot be null or empty");

            // This exception is better as it is more specific
            // ArgumentException(string message, string paramName)
            throw new ArgumentException("Name cannot be null or empty", nameof(Name));
            /*
                Side note:
                The nameof operator in C# returns the string name of a 
                variable, type, or member. If you later rename the 
                property Name, the nameof(Name) will automatically 
                update, avoiding hardcoded strings that could become 
                outdated.
            */
        }
        // This code will not be executed if the exception is thrown
        Name = value;
    }

    /*
        Exercise:
        write a SetAge method that throws an ArgumentOutOfRangeException 
        if the age is not between 0 and 200.

        https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception
    */
    public void SetAge(int age)
    {
        if (age < 0 || age > 200)
        {
            throw new ArgumentOutOfRangeException(nameof(Age), "Age must be 0-200");
        }
        Age = age;
    }

    public bool IsAdult() => Age >= 18;
}